---
# Tasks file for config ntp daemon

- name: seting-up ntp config
  become: true
  ansible.builtin.template:
    src: templates/ntp.conf.j2
    dest: "{{ ntp_configfile }}"
    owner: "{{ ntp_configfile_user }}"
    group: "{{ ntp_configfile_group }}"
    mode: 0644
  notify: "Restart ntp daemons on {{ ansible_system }}"
