---
# Tasks file for install ntp daemon on FreeBSD system

- name: Install ntp daemon on FreeBSD
  become: true
  ansible.builtin.package:
    name: "{{ ntp_package }}"
    state: present

- name: Service ntp on FreeBSD
  become: true
  ansible.builtin.service:
    name: "{{ ntp_service }}"
    enabled: true
    state: started
