---
- name: run versionscheck if enabled
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ lookup('first_found', ntp__vars) }}"

- name: Install ntp
  ansible.builtin.include_tasks: "{{ lookup('first_found', ntp__install) }}"

- name: Configure ntp
  ansible.builtin.include_tasks: config.yml

- name: Configure timezone
  ansible.builtin.include_tasks: zone.yml  
