name: Ansible Lint

on:
  workflow_dispatch:

jobs:
  ansible-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel ansible ansible-lint

      - name: Lint Playbook
        run: ansible-lint serverimages/cloudbuild_rhel9.yaml

      - name: Playbook Run
        run: ansible-playbook -b --connection=local -i 127.0.0.1, main.yml
