name: GCP-Packer-Ubuntu
run-name: GCP-Packer-Ubuntu
on: workflow_dispatch
env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:

  Build-GCP-Ubuntu-Image:

    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ${{ github.workspace }}/serverimages/ubuntu/base

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check ansible
        run: "ansible --version"

     # - id: 'auth'
     #   uses: 'google-github-actions/auth@v1'
     #   with:
     #     workload_identity_provider: 'projects/341535952302/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
     #     service_account: 'gitman@test-ground-403314.iam.gserviceaccount.com'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SC_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3"

      - name: Run `packer init`
        id: init
        run: "packer init -upgrade ."

      - name: Run `packer`
        id: validate
        run: "packer build -var-file=ubuntu.pkrvars.hcl ."
